# Generated by Django 4.2.29 on 2026-05-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallry', '0005_profile_username_profile_bio_profile_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(default='post.jpg', upload_to='post_pics')),
            ],
        ),
    ]
